//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COM526_Week9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conservative
    {
        public int Id { get; set; }
        public string Position { get; set; }
        public string Name { get; set; }
        public bool Usefulness { get; set; }
    }
}
